### ISSUE TITLE
[Mod Support Request] - Pixelmon

### ISSUE THREAD

**Issue by kaymarierose** [babybluetit/Xaeros-Minimap-Modded-Support#68]
* https://pixelmonmod.com/downloads.php
* ~899 Pokémon
* 1.16.5 Forge

**Comment by One-Nub** [comment]
Also interested in this, it seems rather complex because all pokemon entities in-game are displayed as `pixelmon:pixelmon`, and they use their own rendering engine so sprites would have to be made/compiled manually (which could be simplified by using something like https://github.com/msikma/pokesprite to source the sprites from).

**Comment by thexaero** [comment]
@One-Nub Even if all pokemon share the same ID, the variants might already be supported by default if the entity renderer returns a unique texture for each one. The number of pokemon is still huge though.

**Comment by babybluetit** [comment]
Fortunately the renderer does indeed return a unique ID for each pokemon. Still a lot of pokemon to support, but I'm working on it!

**Comment by thexaero** [comment]
@babybluetit That's awesome!

**Comment by kaymarierose** [comment]
@babybluetit You're awesome, thank you!

**Comment by babybluetit** [comment]
Thank you both for your kind words! The pack has now been approved, you can download it from [here](https://www.curseforge.com/minecraft/texture-packs/xaeros-minimap-pixelmon-support).
